spring:
  batch:
    job:
      name: ${job.name:NONE}
    jdbc:
      initialize-schema: always

  datasource:
    hikari:
      danalpay:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/danalpay?useSSL=false&serverTimezone=UTC
        username: root
        password: 1234
      oneapi:
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234

  exposed:
    generate-ddl: true

logging:
  level:
    Exposed: debug
